### ISSUE TITLE
Heatsink substrate

### ISSUE THREAD

**Issue by JDogHerman** [MaslowCNC/PCBs#20]
I might be wrong in this, but would it be good to add a thermal substrate copper pad for the H-Bridge ICs to sit upon?

**Comment by BarbourSmith** [comment]
I think it's a great idea. We actually had one in an early version of the PCB, but I took it out because our PCBA people were having enough trouble and I wanted to make things really really really easy for them. It might be time to put that back in. The ground plane runs right under each chip to make doing exactly that easy.

**Comment by JDogHerman** [comment]
Sorry I opened this and then looked closer at the traces and saw that the traces run underneath the ICs.

**Comment by dmouw25** [comment]
Is it possible to Reopen this?   These packages are designed to dissipate most of the heat through slug on the bottom of the package.  If you notice, the datasheet does not give thermal values for junction to case.   You would likely get better thermal performance with a redesigned PCB and no heatsink.

**Comment by JDogHerman** [comment]
Reopened as a feature request.

**Comment by blurfl** [comment]
I believe this was addressed in the v1.2 layout. @JDogHerman, @dmouw25 does that look correct to you? If so, we could close this.

**Comment by BarbourSmith** [comment]
I second that it was a great suggestion and has been added
