### ISSUE TITLE
Silkscreen is missing LED polarity

### ISSUE THREAD

**Issue by JDogHerman** [MaslowCNC/PCBs#22]
It might be nice to see the LED polarity shown on the silkscreen for those of us that are sadistic enough to build our own boards.

Also why not show a website address? maslow.cnc 👍

**Comment by BarbourSmith** [comment]
Those are both great suggestions

**Comment by blurfl** [comment]
I'm going to be into the design files working on the schematic for [issue #36(https://github.com/MaslowCNC/Electronics/issues/36). I'll open a separate PR to add this and update the board .jpg as well.

**Comment by blurfl** [comment]
Rather than draw an LED symbol, I've put a plus sign opposite the positive end of each of the two LEDs:
<img width="1048" alt="powerdistributionboardlayout-pr2" src="https://user-images.githubusercontent.com/1851315/34809859-bb390dea-f64c-11e7-9b2c-ee2b2248481d.png">

If that's satisfactory, I'll put in a PR with the change.

**Comment by BarbourSmith** [comment]
I think that looks great!

**Comment by BarbourSmith** [comment]
There is a small dot on the LED part, does that not indicate polarity?

![image](https://user-images.githubusercontent.com/9359447/34840006-75105c1c-f6b8-11e7-9097-15d5e36ecbfa.png)

![image](https://user-images.githubusercontent.com/9359447/34840016-84d29250-f6b8-11e7-85b9-24d01673598e.png)

**Comment by BarbourSmith** [comment]
My read of the schematic is that the polarity should be like this:

![image](https://user-images.githubusercontent.com/9359447/34840233-31d9f682-f6b9-11e7-9b73-9fdd33d79e75.png)

![image](https://user-images.githubusercontent.com/9359447/34840255-434b0fd2-f6b9-11e7-8f09-8183aeacd4a3.png)

**Comment by blurfl** [comment]
Thanks Bar, you're right. Hard to turn my thinking around to 12V power plane and routed ground. The dot _does_ indicate polarity, but I think it wouldn't appear on the silkscreen of a PCB in a maker's hand because it's in a keep-out area. The plus would address that. You've got a good point, though - SMD LED's use a dot to mark the cathode end. How best to address the issue, dot-at-cathode or plus-at-anode? @JDogHerman, what's your opinion?

**Comment by BarbourSmith** [comment]
I think the plus is a great idea! I was just pointing out the dot because I was curious what it meant. You are absolutely right that it does not show up anywhere on the PCB. I actually had an email from the manufacturer this morning to confirm the diode directions so even they are confused 😛 

The plus will be much better.

**Comment by blurfl** [comment]
Just to stir the pot, how about:
![screen shot 2018-01-11 at 11 30 55 am](https://user-images.githubusercontent.com/1851315/34843750-3fa13cb6-f6c4-11e7-96ad-3600b36e0d26.jpg)

and
![screen shot 2018-01-11 at 11 31 07 am](https://user-images.githubusercontent.com/1851315/34843759-44cd3906-f6c4-11e7-8b9e-074ebe5f5d2e.jpg)

**Comment by BarbourSmith** [comment]
SLICK! I love it

**Comment by blurfl** [comment]
This was addressed in PR#42 - is it Ok to close this?

**Comment by BarbourSmith** [comment]
Also beautifully taken care of. I vote to close.
